### ISSUE TITLE
Stars won't move along side title.

### ISSUE THREAD

**Issue by emilylavinskas** [emilylavinskas/dsn1676-assignment1#1]
@thomasjbradley – I'm trying to get the two stars to line up beside the Wanted!, but no matter what I try, I cannot get them to move. I've checked with other peoples code, as well as the one you shared with the tutorial for the Exterminate website, and I inputed the same code, but it's still not lining up. 

Here is my HTML & CSS.

``` html

<!DOCTYPE html>
<html lang="en-ca">
<head>
    <meta charset="utf-8">
    <title>Wanted</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="css/grid.css" rel="stylesheet">
    <link href="css/typography.css" rel="stylesheet">
    <link href="css/main.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Abril+Fatface' rel='stylesheet' type='text/css'>
    <meta name="viewport" content="width=device-width,initial-scale=1">
</head>
<body>

<div class="island-half">
    <header class="masthead push">
        <h1 class="title push-0 gutter"><img class="logo" src="images/logo.svg" alt="">Wanted!<img class="logo" src="images/logo.svg" alt=""></h1>
    </header>
</div>

<div class="grid">

</body>
</html>
```

``` css
@-moz-viewport { width: device-width; scale: 1; }
@-ms-viewport { width: device-width; scale: 1; }
@-o-viewport { width: device-width; scale: 1; }
@-webkit-viewport { width: device-width; scale: 1; }
@viewport { width: device-width; scale: 1; }

html {
    margin: 0;
    padding: 0;
    box-sizing: border-box;

    font: normal 100%/1.5 sans-serif;
    -moz-text-size-adjust: 100%;
    -ms-text-size-adjust: 100%;
    -webkit-text-size-adjust: 100%;
    text-size-adjust: 100%;
}

*, *:before, *:after {
    box-sizing: inherit;
}

body {
    margin: 0;
    padding: 0;
    background-color: #E8E5DA;
}

img {
    display: block;
    width: 100%;
}

.title {
    text-shadow: 1.5px 1.5px 0 grey;
    display: inline-block;
    background-color: #E8E5DA;
}

.logo {
    margin: 0 0.2em 0 0;
    width: 1em;
    vertical-align: middle;
}

.masthead {
    background: transparent url("../images/masthead-bg.png") repeat left center;
    text-align: center;
}
```
