### ISSUE TITLE
Icons not showing up in Reward box

### ISSUE THREAD

**Issue by emilylavinskas** [emilylavinskas/dsn1676-assignment1#2]
@thomasjbradley – I've been trying to get the icons to show up in the middle box where the reward goes; I followed the Organizing & Slicing – Multiple Background Images video, and added all the needed code, but it's not showing up.

Here is my HTML for the main content:

``` html
<div class="grid">
            <div class="unit unit-xs-1 unit-s-1 unit-m-1-3 unit-l-1-3 gutter-1-3">
                <img class="image-flex images-border push" src="images/criminal2.jpg" alt="">
            </div>

            <div class="reward-type reward-background reward-icons unit unit-xs-1 unit-s-1 unit-m-1-3 unit-l-1-3 gutter-1-3">
                <p class="reward yotta">Reward</p>
                <p class="number yotta">50 000</p>
                <p class="mega pad-t">For the following crimes:</p>

                <ul>
                    <li class="milli">Space Piracy</li>
                    <li class="milli">Illegal astroid mining</li>
                    <li class="milli">Galactic Treason</li>
                </ul>
            </div>

            <div class="unit unit-xs-1 unit-s-1 unit-m-1-3 unit-l-1-3 gutter-1-3">
                <img class="image-flex images-border push" src="images/criminal1.jpg" alt="">
            </div>
        </div>

    </div>
</div>
```

And here is the CSS:

``` css
.reward-background {
    background-color: #87714F;
    padding: 20px;
}

.reward-icons {
    background-image: url("../images/reward-bottom.svg"), url ("../images/reward-top.svg");
    background-position: center top, center bottom;
    background-repeat: no-repeat;
    background-size: 32px 32px, 32px 32px;
}
```
