### ISSUE TITLE
Borders and Rewards box won't separate

### ISSUE THREAD

**Issue by emilylavinskas** [emilylavinskas/dsn1676-assignment1#3]
@thomasjbradley – Another issue I'm having is that the borders on the images and the rewards box are all touching. 

![screen shot 2015-01-13 at 5 07 17 pm](https://cloud.githubusercontent.com/assets/6373195/5730271/a870bbd6-9b46-11e4-8ce0-dbd5f0bdbe26.png)

Here is the HTML:

``` html
<div class="unit unit-xs-1 unit-s-1 unit-m-1-3 unit-l-1-3 gutter-1-3">
                <img class="image-flex images-border push" src="images/criminal2.jpg" alt="">
            </div>

            <div class="reward-type reward-background reward-icons unit unit-xs-1 unit-s-1 unit-m-1-3 unit-l-1-3 gutter-1-3">
                <p class="reward yotta">Reward</p>
                <p class="number yotta">50 000</p>
                <p class="mega pad-t">For the following crimes:</p>

                <ul>
                    <li class="milli">Space Piracy</li>
                    <li class="milli">Illegal astroid mining</li>
                    <li class="milli">Galactic Treason</li>
                </ul>
            </div>

            <div class="unit unit-xs-1 unit-s-1 unit-m-1-3 unit-l-1-3 gutter-1-3">
                <img class="image-flex images-border push" src="images/criminal1.jpg" alt="">
            </div>
```

And the CSS:

``` css
.image-flex {
    display: block;
    width: 100%;
}

.images-border {
    border-image: url(../images/border-photos.png) 20 20 20 20 stretch stretch;
    border-width: 20px 20px 20px 20px;
}

.reward-background {
    background-color: #87714F;
    padding: 20px;
}
```
